services:
  api-users:
    build: ./vrs-users-service
    ports:
      - 8000:80
    environment:
      - AUTH_API_PATH=${AUTH_API_PATH}
      - USERS_API_PATH=${USERS_API_PATH}
      - USERS_API_KEY=${USERS_API_KEY}
      - AUTH_API_KEY=${AUTH_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_SERVER_PORT=${SMTP_SERVER_PORT}
      - SMTP_SERVER_USER=${SMTP_SERVER_USER}
      - SMTP_SERVER_PASSWORD=${SMTP_SERVER_PASSWORD}
      - MONGO_CONNECTION_STRING=${USERS_MONGO_CONNECTION_STRING}
    depends_on:
      - users-db

  users-db:
    image: mongo:7.0
    ports:
      - 27017:27017

  api-auth:
    build: ./vrs-auth-service
    ports:
      - 8001:80
    environment:
      - USERS_API_PATH=${USERS_API_PATH}
      - USERS_API_KEY=${USERS_API_KEY}
      - AUTH_API_KEY=${AUTH_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - REDIS_CONNECTION_STRING=${AUTH_REDIS_CONNECTION_STRING}
    depends_on:
      - auth-db

  auth-db:
    image: redis:7.2.4
    ports:
      - 6379:6379

  api-routing-problems:
    build: ./vrs-users-service
    ports:
      - 8002:80
    environment:
      - AUTH_API_PATH=${AUTH_API_PATH}
      - AUTH_API_KEY=${AUTH_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MONGO_CONNECTION_STRING=${ROUTING_PROBLEMS_MONGO_CONNECTION_STRING}
    depends_on:
      - routing-problems-db

  routing-problems-db:
    image: mongo:7.0
    ports:
      - 27018:27017

  vrp-solver:
    build: ./vrs-vrp-solver
    ports:
      - 8003:80
